package ai;

import org.json.JSONArray;
import org.json.JSONObject;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

public class AIDetector {

    public static class AIDetectionResult {
        public final int probability;
        public final String reason;
        public final String error;

        public AIDetectionResult(int probability, String reason, String error) {
            this.probability = probability;
            this.reason = reason;
            this.error = error;
        }
    }

    public static AIDetectionResult detect(String codeText) {
        String apiKey = System.getenv("GEMINI_API_KEY");
        if (apiKey == null || apiKey.trim().isEmpty()) {
            return new AIDetectionResult(0, null, "GEMINI_API_KEY environment variable not set.");
        }

        try {
            HttpClient client = HttpClient.newBuilder()
                    .connectTimeout(Duration.ofSeconds(10))
                    .build();

            JSONObject payload = new JSONObject();
            JSONArray contents = new JSONArray();
            JSONObject content = new JSONObject();
            JSONObject part = new JSONObject();
            
            String prompt = "Analyze the following source code and determine the probability (0 to 100) that it was generated by an AI assistant. Consider factors like excessive boilerplate, perfect but robotic comments, unusual consistency, or known AI patterns. Return ONLY a JSON object with two fields: 'probability' (an integer from 0 to 100) and 'reason' (a short 1-2 sentence explanation).\n\nCode:\n" + codeText;
            
            part.put("text", prompt);
            content.put("parts", new JSONArray().put(part));
            contents.put(content);
            payload.put("contents", contents);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + apiKey))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(payload.toString()))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() != 200) {
                return new AIDetectionResult(0, null, "API Error: " + response.statusCode());
            }

            JSONObject jsonRes = new JSONObject(response.body());
            String responseText = jsonRes.getJSONArray("candidates")
                    .getJSONObject(0)
                    .getJSONObject("content")
                    .getJSONArray("parts")
                    .getJSONObject(0)
                    .getString("text");
            
            // Clean markdown JSON wrapping if present
            responseText = responseText.replaceAll("```json", "").replaceAll("```", "").trim();
            JSONObject parsed = new JSONObject(responseText);
            
            return new AIDetectionResult(
                    parsed.optInt("probability", 0),
                    parsed.optString("reason", "No reason provided."),
                    null
            );

        } catch (Exception e) {
            return new AIDetectionResult(0, null, "Detection failed: " + e.getMessage());
        }
    }
}
